// Code generated by mockery. DO NOT EDIT.

package mock_syncinterfaces

import mock "github.com/stretchr/testify/mock"

// StateBlobSequencer is an autogenerated mock type for the StateBlobSequencer type
type StateBlobSequencer struct {
	mock.Mock
}

type StateBlobSequencer_Expecter struct {
	mock *mock.Mock
}

func (_m *StateBlobSequencer) EXPECT() *StateBlobSequencer_Expecter {
	return &StateBlobSequencer_Expecter{mock: &_m.Mock}
}

// NewStateBlobSequencer creates a new instance of StateBlobSequencer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateBlobSequencer(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateBlobSequencer {
	mock := &StateBlobSequencer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
